language: python

install:
  - "wget -q -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -q -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list"
  - "sudo apt-get update"
  - "sudo apt-get install $(apt-cache depends python-spotify | awk '$2 !~ /spotify/ {print $2}')"
  - "sudo apt-get install python-all-dev libmockspotify-dev libspotify-dev"
  - "sudo python setup.py install --with-mock"

before_script:
  - "rm $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt"

script: nosetests

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
